### ISSUE TITLE
Crash in iOS 15 with Xcode 13

### ISSUE THREAD

**Issue by sehaswaran** [eu-digital-green-certificates/dgca-app-core-ios#106]
In Scan.swift file, 
processClassification method, 
this line of code [.Aztec, .QR, .DataMatrix] is crashing. 

as per iOS Document,

    @available(macOS, introduced: 10.13, deprecated: 12.0, renamed: "aztec")
    @available(iOS, introduced: 11.0, deprecated: 15.0, renamed: "aztec")
    @available(tvOS, introduced: 11.0, deprecated: 15.0, renamed: "aztec")
    public static let Aztec: VNBarcodeSymbology

It needs to be modified to as renamed names to avoid

[.aztec, .qr, .dataMatrix]

**Comment by alexchornyi** [comment]
fixed. Please check latest version

**Comment by alexchornyi** [comment]
done
