### ISSUE TITLE
Setup Basic Testcases for Decoder

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-app-core-ios#29]
The testdata repo is filled with a lot of testdata. Please implement Decoder Unit Tests for the following list: 
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/BasicDgcTestsList.md

**Comment by yspreen** [comment]
Progress of this is tracked in https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/issues/51

The branch is here: https://github.com/eu-digital-green-certificates/dgca-app-core-ios/pull/27
