### ISSUE TITLE
Zero Tags in Dates are not supported

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-app-core-ios#39]
The current SwiftCBOR ignores the tagging of date times (just a support for tag=1 inserted). The swift cbor library should be fixed to accept this QR codes. (https://github.com/PaulBallmann/SwiftCBOR/commit/b76024995f6909e4615f943c7a03268fd29778fc) 

See this code here: https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/png/7.png

**Comment by SchulzeStTSI** [comment]
@yspreen Can you have a look on it?

**Comment by yspreen** [comment]
I don’t really understand the issue to be honest
-- 
Yannick Spreen

**Comment by SchulzeStTSI** [comment]
The problem is the following: The CBOR rfc describes in the https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.1 that protocols can express date-times as tagged representations. Means with 0 tag(string), 1 tag (POSIX) etc. The most of the libaries support this tagging by resolving the tags to the correct format during the decoding. Unfortunately some libaries don't set tags during the encoding (e.g. the CBORMapper of Jackson) because they are interpreting "string" just as string, doesn't matter whats inside. But there are libaries which are set the tag if there is a date-time. The swift cbor libary just supports the 1 Tag which is currently out of scope, but the zero tag is missing. This leads during the decoding to undefined values.

**Comment by yspreen** [comment]
So wait, what does Paul's PR have to do with it? Should we just switch to our fork of CBOR instead of the official lib trunk? Because the commit you mentioned seems to fix it

**Comment by SchulzeStTSI** [comment]
Paul created a fork of swift cbor to try out the fix. The fix works so far we see, but now we need to fork it our repo to integrate it in the core lib. Parallel to that we should create a pull request in the offical branch to deliver the fix. Later we can migrate back to the offical one, when they commit it(I don't know how fast they are). If this works we should let run the unit tests again to see if the tagged codes are accepted.

**Comment by PaulBallmann** [comment]
I forked the repo with the fix into our org. Pull request has been opened that addresses the issue.
