### ISSUE TITLE
Architecture proposal - removing UI in SDK Core

### ISSUE THREAD

**Issue by tjaussoin-luna** [eu-digital-green-certificates/dgca-app-core-ios#40]
## Feature description

We're implementing the DGC in TousAntiCovid 🇫🇷

There is UI logic related to the client apps (Verifier et Wallet) that has been centralized in SwiftDGC: there are some pieces of UI, network calls and localization management. Ideally, it would be perfect to only have the pure business logic (parsing + signature check), 100% separated from the client application that will use it.

With that in mind, the changes could help as well to ease the integration of this SDK in apps already on Stores, and make it as light as possible:

- We removed these files from SwiftDGC :

    * Scan.swift
    * UIViewController.swift
    * UITableViewCell.swift
    * UIImage.swift
    * SquareViewFinder.swift
    * AppVersionCell.swift
    * Assets.xcassets
    * ContextConnection.Swift
  
- We could therefore remove the dependency to Alamofire.
-  The HCert model is proposed not to embed anything related to the UI, meaning the info variable that contains localized labels to display.
- It's very useful to have in the SDK the labels to localize everything with a code (for vaccins, tests...). However, the strings used by the UI e.g. "Certificate Type" or "Date of Birth" is already managed on the client app side. That would be useful to have an architecture in which the localization is managed outside the SDK (i.e. managed on the client side). However, that would be helpful to have the SDK managing all codes in all languages (product codes, manufacturers, ...): we would have in one place for all UE countries all the multilingual labels corresponding to the codes.

- In the HCert object, there is a validityFailures array which is containing a list of strings describing the errors. It would be better to have a list of error codes or enum values to be able to map this to description strings on the client app side.

## Problem and motivation

The idea is to split this "core", without UI at all.

## Is this something you're interested in working on

Yes

**Comment by yspreen** [comment]
See https://github.com/eu-digital-green-certificates/dgca-app-core-ios/issues/41#issuecomment-849489487

**Comment by tjaussoin-luna** [comment]
Could we create a new repo with this SDK code (we already have, in fact)?

**Comment by yspreen** [comment]
Let's keep the discussion to #41 so that we don't duplicate ever message

**Comment by PaulBallmann** [comment]
Closed in #41 - https://github.com/eu-digital-green-certificates/dgca-app-core-ios/issues/41#issuecomment-883199085
