### ISSUE TITLE
iOS 11 support

### ISSUE THREAD

**Issue by tjaussoin-luna** [eu-digital-green-certificates/dgca-app-core-ios#41]
## Current Implementation

No support of iOS 11+

## Suggested Enhancement

To support iOS 11, we updated the function “pubKey(from b64EncodedCert: String)” X509.swift like this:

```swift
public static func pubKey(from b64EncodedCert: String) -> SecKey? {
      guard let encodedCertData = Data(base64Encoded: b64EncodedCert) else { return nil }
      guard let cert = SecCertificateCreateWithData(nil, encodedCertData as CFData) else { return nil }
      let publicKey: SecKey?
      if #available(iOS 12.0, *) {
        publicKey = SecCertificateCopyKey(cert)
      } else {
        publicKey = SecCertificateCopyPublicKey(cert)
      }
      return publicKey
    }
```

## Expected Benefits

Support of iOS 11+

**Comment by PaulBallmann** [comment]
Supporting iOS 11 in all other applications would make it harder to maintain. I guess there is no need for iOS 11 support unless @yspreen disagrees.

**Comment by tjaussoin-luna** [comment]
Hi @PaulBallmann - in France, we support iOS 11+ in our French app (hence our modification).

**Comment by yspreen** [comment]
What you're talking about requires #40 as a dependency.

We're deploying two apps with lots of duplicate code. For our architecture, this module is the ideal solution and requires iOS 12.

I agree though, splitting would be a big help in unifying implementations across countries, and lowering the bar to include this repo as a dependency. I propose the following architecture:

- A Swift DGC library for health cert functionality
- One library called app-core including the above lib as a dependency and adds shared UI

Project management will have to evaluate the time cost of this, and who will work on that redesign. Sadly it's not something we can just do right now for time constraint reasons. I agree, it would be a good asset to have.

**Comment by tjaussoin-luna** [comment]
Could we create a new repo with this SDK code (we already have, in fact)?

**Comment by yspreen** [comment]
I'm not sure how your proposal differs from my last comment

**Comment by tjaussoin-luna** [comment]
The fact that we do it now, if you don't have time :)

**Comment by PaulBallmann** [comment]
Since this issue and #40 has been open since May, I will close this issue now. The workload is currently out of scope for us. It would mean a complete overhaul of the SDKs for all of our applications while the benefit is fairly low. Also, any other app that builds on our SDKs would have to make a switch too. If someone else wants to commit to providing such an upgrade and maintaining it and also making sure we maintain compatibility with every other member state, we can discuss it via mail.
