### ISSUE TITLE
Support CWT Tags 

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-app-core-ios#44]
Problem

The CWT RFC allows to tag the COSE Objects with a CWT Tag (61) which leads in the current implementation to a n rejection of the QR Code. 

Proposed solution

The object should be checked for tag 61, if available the cose message should processed, otherwise the normal cose message is processed directly.

This can be solved maybe by a decoder decorator: https://github.com/SchulzeStTSI/dgca-app-core-ios/tree/fix/tag-61

The COSE-JAVA can handle this, maybe the fix has to be done in the SWIFT-CBOR library.

**Comment by yspreen** [comment]
https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/SE/png/5.png

**Comment by SchulzeStTSI** [comment]
Another related fix can be found here: https://github.com/ehn-digital-green-development/ValidationCore/blob/main/Sources/ValidationCore/Cose.swift#L80
