### ISSUE TITLE
IOS APP crashes on scann of QR

### ISSUE THREAD

**Issue by Mark-Selezenev** [eu-digital-green-certificates/dgca-app-core-ios#56]
Once QRs from some countries are scanned then the IOS APP crashes and does not produce any result. EE doesn't use IOS version but other countries that tried had this issue.

## Steps to reproduce the issue

1) Go to https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/EE/png
2) Open the IOS APP
3) Scan one of the QRs

Expected result: Sertificate is valid against Test or Acceptance Test.
Actual result: Crash

## Technical details

Can't provide any specific technical details or logs. But the suggestion on the call at 5 yesterday was that IOS has problems with some signature calculations/verifications.

## Possible Fix

If it is indeed the calculations/verifications then fix the algorithm implementation.

## Additional context

Switzerlands QRs were also producing a crash as I was told.

**Comment by jozemlakar** [comment]
I reported this issue. I had not had the time to analyze it further. I used latest changes made by TSI (yesterday).

**Comment by jozemlakar** [comment]
Can you please add JSON, so we can crosscheck payload when we debug? Specifiy the respective png.

**Comment by jozemlakar** [comment]
I analyzed the best I could. I do believe the CBOR is not ok. This is the CBOR that is read, and it does not decode on cbor.me

D2844DA24489A4A284AF250919D126A05912AA441A61ACCB561A60BF7D516245453913A11A4617681AA62646E2626D616D4F52472D313030303031363939627670674A3037425830336264746A323032312D30342D313662636F624545626369781E30312F45452F5449532F3943304B41564949594837435A414230324F234F626D706C45552F312F32312F3135323962697363544953627364262746769383430353339303036636E616DA463666E747745453C3C3C3C3C3C3C3C3C3C3C3C4C4153543C4E414D4562666E77656533383331303237353038392D6C6173742D6E616D6563676E74781845453C3C3C3C3C3C3C3C3C3C3C3C46495253543C4E414D4562676E7818656533383331303237353038392D66697273742D6E616D656376657265312E302E3063646F626A313938332D31302D32375840C4C39FF5CC699F414A13737BB2D2329351804C8E92F4B679ED1D186FF4FF6851AC39F751EC853BF9F3AF851C713E198B7B1E699CEBEB385190D9A8

**Comment by Mark-Selezenev** [comment]
@jozemlakar Did you implement the fix from two weeks ago. Some country is saying it works for them.

**Comment by PaulBallmann** [comment]
New PR addresses the issue. Tested with: https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/EE/png [test, recovery, vaccination]

**Comment by jozemlakar** [comment]
I can confirm now all three DGCs by EE are valid for SI.
