### ISSUE TITLE
Unexpected coalescence of statements when multiple are available

### ISSUE THREAD

**Issue by tom139** [eu-digital-green-certificates/dgca-app-core-ios#75]
## Describe the bug

HCert class only exposes a single property `.type: HCertType` and a single property  statement; this is a problem when a certificate contains multiple statements.

For example the pass of a citizen with a test reporting their state as positive could be marked as "valid" because they also have a recovery statement (even if the recovery happened 1 year ago).

## Expected behavior

I think all statements should be evaluated, not only the last one, see:

https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/53d918f8fac41c40fa494878fdf94810e712b412/Sources/Models/HCert.swift#L305-L319

Since the evaluation order is `testStatements + vaccineStatements + recoveryStatements` and only the last is used to evaluate the type, a pass holding a recovery **and** a _positive_ test result (like the example from below) will be marked as valid.

This is a critical behavior of the current version of the iOS app, as the user is currently positive to the test but marked _valid_.

## Steps to reproduce the issue

The following payload describes a person being currently positive (by a test in the last 24 hours) after having recovered from COVID-19 some months ago in April. Since the only statement exposed by the `HCert` class is the recovery one, the pass will qualify as valid even if the owner is infected.

```ts
{
    "ver": "1.2.1",
    "nam": {
        "fn": "Musterfrau-G\u00f6\u00dfinger",
        "gn": "Gabriele",
        "fnt": "MUSTERFRAU<GOESSINGER",
        "gnt": "GABRIELE"
    },
    "dob": "1998-02-26",
   "t": [
        {
            "tg": "840539006",
            "tt": "LP217198-3",
            "ma": "1232",
            "sc": "2021-02-20T12:34:56+00:00", // set to 24h ago
            "tr": "260373001",  // tested positive
            "tc": "Testing center Vienna 1",
            "co": "AT",
            "is": "Ministry of Health, Austria",
            "ci": "URN:UVCI:01:AT:71EE2559DE38C6BF7304FB65A1A451EC#3"
        }
    ],
    "r": [
        {
            "tg": "840539006",
            "fr": "2021-02-20",
            "co": "AT",
            "is": "Ministry of Health, Austria",
            "df": "2021-04-04",
            "du": "2021-10-04",
            "ci": "URN:UVCI:01:AT:858CC18CFCF5965EF82F60E493349AA5#K"
        }
    ]
}
```

## Technical details

- Host Machine OS (Windows/Linux/Mac): iOS

## Possible Fix

1. Exposing all statements by marking the existing property as `public`
2. Removing the `statement` and `type` properties as they may be misleading

I think validation of *all* statements should be left to the app implementing validation (i.e. wallet and verifier).

**Comment by SchulzeStTSI** [comment]
Hello @tom139. Thank you for this contribution. We have not added this feature, because multiple events are forbidden by the regulation.  There is a paragraph which says that a DCC shall not contain medical events of prior actions. This was also reflected in the latest dcc schema 1.3 (https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.3.0/DCC.schema.json)  where "oneOf" was added to avoid that multiple events will be issued. From this perspective, I think we can close this bug, because everything works as described.

**Comment by daniel-eder** [comment]
Closing this - feel free to comment if there is more to be added from your perspective and we'll reopen.

**Comment by tom139** [comment]
Thank you for your time, the described behaviour is explicit in [JSON Schema Specification - Groups for certificate type specific information](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf#page5), but I missed it.

> **Groups for certificate type specific information**
> The JSON Schema supports three groups of entries encompassing certificate type specific information. Each EUDCC MUST contain exactly 1 (one) group. Empty groups are not allowed.

Thanks for your great work!
