### ISSUE TITLE
HC1 missing in QR Code stored in the ios Wallet

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-app-core-ios#83]
Upon Scanning the QR Code in the iOS Wallet, the HC1 prefix is removed.
The resultant QR Code that is saved in the Wallet is invalid, as it's missing the HC1 prefix.

in HCert.swift:
```
  static func parsePrefix(_ payloadString: String, errors: ParseErrors?) -> String {
    var payloadString = payloadString
    var foundPrefix = false
    for prefix in Self.supportedPrefixes {
      if payloadString.starts(with: prefix) {
        payloadString = String(payloadString.dropFirst(prefix.count))
        foundPrefix = true
        break
      }
    }
    if !foundPrefix {
      errors?.errors.append(.prefix)
    }
    return payloadString
  }

```

The above line removes the HC1 prefix (which is correct at this point)
`payloadString = String(payloadString.dropFirst(prefix.count))`

However, later in HCERT+UIKit.swift, this HC1 is never returned to the payLoad when saving the new QR Code that is saved in the wallet.

```
  func makeQrCode() -> UIImage? {
    let data = payloadString.data(using: String.Encoding.ascii)

    if let filter = CIFilter(name: "CIQRCodeGenerator") {
      filter.setValue(data, forKey: "inputMessage")
      let transform = CGAffineTransform(scaleX: 3, y: 3)

      if let output = filter.outputImage?.transformed(by: transform) {
        return UIImage(ciImage: output)
      }
    }

    return nil
  }
```

Either we need to either prepend the HC1 back when making the QRCode (which for me is not a correct solution, 
or maintain the Original QR Code string (version without trimming), and utalize this to save the QRCode in the makeQrCode function.

**Comment by psavva** [comment]
@SchulzeStTSI Please can you review this, as it may be painful for many countries.

It's probably going to require that Verifiers will need to test against this specific issue, and "accept" this as a valid QR Code.
I know that Belgium, Greece will currently fail using the current bug in place.

**Comment by dirkx** [comment]
So this is indeed a very serious issue / bug. I suggest:

* TSI priorities investigtion + which countries are affected
* A small implementation note is written
* @psavva or TSI tries to get some example cases in the main body of test sets

And then we do 3 things (in order urgency):
* We sent out an urgent communication to the 24x7 contacts that they will see this at the border
* We sent out an urgent comms to the implementors to test & introduce a workaround in their verifiers (for those countries)
* TSI fixes this bug in their code and pushes this out to those that use their code for the citizen app.

**Comment by ryanbnl** [comment]
The change was made 3 months ago! Are we sure that this bug is manifesting? This should never have passed even the most rudimentary QA.

Here's the offending commit: https://github.com/eu-digital-green-certificates/dgca-app-core-ios/commit/a8a2b2f51d33dd9c25c5f2eeb373cee43683e895

**Comment by ryanbnl** [comment]
@psavva and I have reproduced this bug in the Cyprus app, in production!

**Comment by psavva** [comment]
May I suggest a routine that checks for the invalid QR code and prepends the HC1: to the exciting QR codes on first startup after the fix.

This would act as a datafix for the exciting QR Codes without the HC1 prefix.

This would also avoid a mass replacement of QR codes on the wallets by citizens, and only required this extra logic during startup...

**Comment by dirkx** [comment]
Couple of months ago I suggested to the TSYS devs to simply check for HC1 at the start; and remove it if present; and just take it from there. As back then as a transition.

**Comment by alexchornyi** [comment]
@psavva fixed in #86 Please take a look, if all working correct.

**Comment by dirkx** [comment]
I would have hoped for at least the 4 permutation test cases too ! As to prevent this from sneaking in again!

**Comment by francoiskarman** [comment]
As this issue is now "closed", do we need to adapt verifiers app as well to manage this case? Or can we consider that all QRCodes are now corrected ?

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
Our Verifier-Apps can read codes with and without the HC1-Prefix.
Anyway, all codes stored in our Wallet-Apps will be correct and include the HC1-Prefix.

**Comment by dirkx** [comment]
> Our Verifier-Apps can read codes with and without the HC1-Prefix.
> Anyway, all codes stored in our Wallet-Apps will be correct and include the HC1-Prefix.
> 
> 
Do you have a list of which countries use yours/these verifier apps ? And a list of which countries use yours/the affected wallet apps ?
